version: '3.8'

services:
  db:
    image: postgres:13.12-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/create-liquibase-changes-schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db

  app:
    build: ./
    container_name: app
    ports:
      - "8080:8080"
    environment:
      DB_SERVER: db
    depends_on:
      - db
