version: '3.8'

services:
  database:
    image: postgres:13.12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/create-liquibase-changes-schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
