version: '3.8'

services:
  db:
    image: postgres:13.12-alpine
    container_name: db
    restart: always
    volumes:
      - ./src/main/resources/create-liquibase-changes-schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"

  hazelcast:
    image: "hazelcast/hazelcast:5.0.5"
    container_name: hazelcast
    environment:
      HZ_NETWORK_PUBLICADDRESS: "127.0.0.1:5701"
      HZ_NETWORK_RESTAPI_ENABLED: "true"
      HZ_CLUSTERNAME: "hazelcast_cluster"
    ports:
      - "5701:5701"

  management-center:
    image: "hazelcast/management-center:5.3.2"
    container_name: management-center
    environment:
      MC_ADMIN_PASSWORD: password1
      MC_ADMIN_USER: admin
      MC_INIT_CMD: "./bin/mc-conf.sh cluster list | grep -q 'dev' || ./bin/mc-conf.sh cluster add -H=/data -ma 192.168.0.1:5701 -cn dev"
    ports:
      - "10080:8080"
    depends_on:
      - hazelcast

  app:
    build: ./
    container_name: app
    environment:
      DB_SERVER: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "8080:8080"
    depends_on:
      - db
      - management-center
