###
# delete as user

DELETE http://localhost:8080/api/users/3
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZXhhbXBsZUBtYWlsLmNvbSIsInNjb3BlIjoiIn0.u1jIZHrdYBObhAWfYThy5aYgdXCklc3wQOoJc7MJ3tTSeqK8H_apisc5_X39n5gLeRIN4R2ejdoZ0vjHxXN3R8cbZTJRKg6hsD_7RyBeInFg9kYOXlv38uapwgkTo9W3cvYJmGUygcl2yfI2Wk5MmdCGzTZt2oMrVSERCucr4CqjQtaWYLcjwBxZLhAfJGSSL11LaJAbxSMpR0Fe2NVxp85WZpGmWptbDiAY2tPOvOGs13tofQquniFrqG2btDn77iwbhabx9z03BhXBQJViywBykjXEmkI4_jR-YPqtfs82K6ydQplhqErsR9komY-FlEwzbWVWfEVcq3mY2-ATKQ

###
# delete as admin

DELETE http://localhost:8080/api/users/3
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW5AbWFpbC5jb20iLCJzY29wZSI6IlVTRVIuREVMRVRFIn0.NiOJUEfWXoleSpVgw9vHhWYoRk0sAL1MgjZ5oHzOJ69PO7NggTpFf-_OyZPTnxceYyAZFl5QpvmKnoxiIUIyRBz-kYNAAhtFAkfpuNTU60vC-nprLmxkhZYCZrsK_iRgNw8OViN5lDgr10ydtXJfmq7Bp6VYNWFvgCcTXAMvTUDjolRcE0BcSdcgJRoyse4cVYIVteeMxyccUR57aEf3tcxaFlUGh7DVxysZxdbBev5ELil6W3dk9vCAOy_K0nETFYGDA-PCbLR-VkUKHG14ajzaX8CHW7vmj_Zuijy5-GQDNre5RkjDdc82siSeNQtgKNG2wcaAQOZoVtVZ_rpnNQ
