###
# login as user

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "pass"
}

###
# login as updated user

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "updated@mail.com",
  "password": "new5pass!"
}

###
# login as admin

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "pass"
}
