PUT http://localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZXhhbXBsZUBtYWlsLmNvbSIsInNjb3BlIjoiIn0.u1jIZHrdYBObhAWfYThy5aYgdXCklc3wQOoJc7MJ3tTSeqK8H_apisc5_X39n5gLeRIN4R2ejdoZ0vjHxXN3R8cbZTJRKg6hsD_7RyBeInFg9kYOXlv38uapwgkTo9W3cvYJmGUygcl2yfI2Wk5MmdCGzTZt2oMrVSERCucr4CqjQtaWYLcjwBxZLhAfJGSSL11LaJAbxSMpR0Fe2NVxp85WZpGmWptbDiAY2tPOvOGs13tofQquniFrqG2btDn77iwbhabx9z03BhXBQJViywBykjXEmkI4_jR-YPqtfs82K6ydQplhqErsR9komY-FlEwzbWVWfEVcq3mY2-ATKQ

{
  "userName": "Mike Booster",
  "email": "updated@mail.com",
  "password": "new5pass!"
}
